# Generated by Django 3.0.4 on 2020-03-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20200305_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
